management:
  endpoints:
    web:
      exposure:
        include: health

kafka:
  properties:
    application.id: kstreamplify-demo-livenesslink-id
    bootstrap.servers: localhost:19092
    schema.registry.url: http://localhost:8081
    auto.offset.reset: earliest
    state.dir: /var/kstreamplify-demo-livenesslink
    processing.guarantee: exactly_once_v2

logging:
  level:
    ROOT: WARN
    org.apache.kafka: INFO